const messageHeader = "<div style='width:600px;font-family: Arial,Helvetica,sans-serif; text-decoration: none; margin:auto; font-size: 14px;'><div style='background: linear-gradient(102.6deg, #3795EB 17.39%, #63D2EB 72.47%); color:#fff; padding:10px;text-align: center;font-size: 18px;'><span style='margin-right: 10px'><img width=70 height=70 src='https://res.cloudinary.com/jhayx/image/upload/v1575807679/Asset_1.1_em0lfg.png'></span></div><div style='padding:15px'>";
const messageFooter = "<p style='margin-top:20px; margin-bottom:0px; color: rgb(106, 108, 111); line-height: 1.35em;'>Thank you,</p><p style='margin-top:0px; margin-bottom:5px; color: rgb(106, 108, 111); line-height: 1.35em;'>The GidiGas Team</p></div><div style='background: linear-gradient(102.6deg, #3795EB 17.39%, #63D2EB 72.47%); color:#fff; padding:7px'></div></div>";

const resetpasswordMessage = (surname, token) => {
  const message = {
    subject: 'Reset GidiGas Password',
    html: `${messageHeader}
            <p>Dear <span style='text-transform: capitalize;'>${surname}</span>,</p>
            <p>You requested for a password reset. Click on the button below to confirm this action.</p>
            <p style='margin-top:20px;text-align:center'><a style='text-decoration:none;padding:10px;background: linear-gradient(102.6deg, #3795EB 17.39%, #63D2EB 72.47%);color:#ffffff;border-radius:5px;' href='${process.env.SERVER_URL}/auth/passwordresetverify/${token}'>Reset Password</a></p>
            <p>or the link below</p>
            ${process.env.SERVER_URL}/auth/passwordresetverify/${token}
            ${messageFooter}`,
  };
  return message;
};

const adminpasswordMessage = (surname, token, password) => {
  const message = {
    subject: 'Reset GidiGas Admin Password',
    html: `${messageHeader}
            <p>Dear <span style='text-transform: capitalize;'>${surname}</span>,</p>
            <p>A new password was autogenerated for your account.</p>
            <p>Your new password is : ${password}</p>
            <p>Click on the button below to change the auto generated password.</p>
            <p style='margin-top:20px;text-align:center'><a style='text-decoration:none;padding:10px;background: linear-gradient(102.6deg, #3795EB 17.39%, #63D2EB 72.47%);color:#ffffff;border-radius:5px;' href='${process.env.SERVER_URL}/auth/passwordresetverify/${token}'>Reset Password</a></p>
            <p>or click the link below</p>
            ${process.env.SERVER_URL}/auth/passwordresetverify/${token}
            ${messageFooter}`,
  };
  return message;
};

export {
  resetpasswordMessage,
  adminpasswordMessage
};
